import { Dept } from './dept';

export const DEPTS: Dept[] = [

{ name: 'Aerospace Engineering', link: 'Aerospace Engineering', courses: [
"AE201A-Introduction To Aerospace Engineering",
"AE211A-Incompressible Aerodynamics",
"AE251A-Experiments In Aerospace Engineering-I",
"AE311A-Compressible Aerodynamics",
"AE321A-Flight Mechanics I",
"AE322A-Flight Mechanics- II",
"AE331A- Introduction to Aerospace Structures",
"AE341A-Aerospace Propulsion",
"AE345A-Spacecraft Guidance Navigation And Control",
"AE351A-Experiments In Aerospace Engineering -II",
"AE361A-Aeromodel Design and Fabrication",
"AE391A-UG Project (UGP-I)",
"AE401A-Technical Communication",
"AE421A-Experiments in flight mechanics",
"AE441A-Turbo-Machinery",
"AE451A-Experiments in Aerospace Engineering",
"AE461A-Aircraft Design-I",
"AE462A-Aircraft Design-II",
"AE471A-B Tech Project",
"AE481A-Boundary Layer Theory",
"AE601A-Intro to Aerospace Engg.",
"AE602A-Mathematics For Aerospace Engg.",
"AE603A-Introduction To Scientific Computing",
"AE604A-Computational Fluid Mechanics",
"AE605A-Advanced Computational Fluid Mechanics",
"AE610A-Aerodynamics-I",
"AE611A0Measurements In Fluid Mechanics",
"AE612A-Aerodynamics II",
"AE614A-Viscous Flows",
"AE615A- Advanced Computational Methods In CFD",
"AE617A-Boundary Layer Instability And Transition",
"AE618A-Finite Element Methods For Fluid Dynamics",
"AE621A-Turbulence",
"AE622A-Computational Fluid Dynamics",
"AE625A-Transition And Turbulence",
"AE628A-Continuum Hypersonic Aerodynamics",
"AE629A-Advances In Wind Energy Conversion",
"AE640A-Autonomous Navigation",
"AE641A-Space Dynamics-I",
"AE645A-Spacecraft Guidance Navigation And Control ",
"AE647A-Flight Dynamics",
"AE648A-Flight Stability And Control",
"AE649A-Automatic Control Of Aircraft Rockets And Spacecraft",
"AE650A-Fundamental Of Aerospace Propulsion - I",
"AE652A-Aircraft Propulsion",
"AE653A-Thermal Turbomachinery",
"AE657A-Airbreathing Missile Propulsion",
"AE658A-Numerical Modeling Of Chemically Reacting Flows",
"AE660A-Preliminary Design Of Helicopter",
"AE662A-Rocket Engine Design",
"AE670A-Aerospace Structural Analysis - I",
"AE672A-Solid Mechanics",
"AE673A-Rocket And Missile Structures",
"AE675A-Introduction To Finite Element Methods",
"AE676A-Aeroelasticity",
"AE678A-Theory of Vibrations",
"AE681A-Composite Materials",
"AE683A-Random Vibrations",
"AE684A- Aircraft Materials And Processes",
"AE685A- Deterministic and Random Vibration",
"AE686A-Helicopter Theory: Dynamics And Aeroelasticity",
"AE687A-Aerospace Struc Analysis II",
"AE688A-Dynamics And Vibration",
"AE689A-Introduction To The Theory Of Smart Structures",
"AE690A-High Temperature Gas Dynamics",
"AE692A-Mechanics Of Highly Deformable Structures",
"AE694A-Acoustics In Fluids",
"AE696A-Instrumentation, Measurements And Experiments In Fluids",
"AE698A- Intro To Virtual Instrumentation",
"AE701A-Nonlinear Finite Element Method",
"AE747A-",
"AE751A-Fundamentals Of Liquid Atomization",
"AE752A-Principles Of Acousticsv",
"AE753A-Theory Of Combustion",
"AE754A-Turbulent Combustion",
"AE777A-Optimal Space Flight Control",
"ESO202A-Mechanics of Solids"
] },
  
{ name: 'Biological Sciences and Bio-engineering', link: 'Biological Sciences and Bio-engineering', courses: [
"BSE211A-Organ System, Physiology and Anatomy",
"BSE221A-BIOCHEMISTRY",
"BSE222A-Biochemical Engineering",
"BSE223A-Biochemistry and Biochemical Engineering Lab",
"BSE301A-Scientific and Professional Communication",
"BSE311A-Molecular Cell Biology",
"BSE312A-Molecular Biology Lab",
"BSE321A-Structural Biology",
"BSE322A-Bioinformatics and Computational Biology",
"BSE398A-UG PROJECT (UGP-I)",
"BSE399A-UG PROJECT (UGP-II)",
"BSE411A-BIOMATERIALS",
"BSE412A-Biomaterial, Physiology and Bio-MEMS Laboratory",
"BSE421A-Tissue Engineering",
"BSE492A-Methods in Biotechnology-I, Experimental Bioseperation",
"BSE498A-UG PROJECT (UGP-III) ",
"BSE499A-Under Graduate Project II",
"BSE601A-Professional Communication",
"BSE602A-Laboratory Methods",
"BSE611A-Modern Instrumental Methods in Biological Sciences",
"BSE612A-Biochemical Engineering",
"BSE613A-BIOMATERIALS",
"BSE614A-Tissue Engineering",
"BSE615A-BIOELECTRICITY",
"BSE616A-BIOPHARMACEUTICALS",
"BSE621A-Modern Instrumental Methods in Biological Sciences",
"BSE629A-NEUROBIOLOGY",
"BSE630A-Developmental Biology I",
"BSE631A-Biochemistry Structural Biology",
"BSE632A-Structural Basic of Protein Function",
"BSE633A-Bioinformatics and Computational Biology",
"BSE634A-FUNCTIONAL GENOMICS",
"BSE636A-FUNCTIONAL GENOMICS",
"BSE640A-BIOMATERIALS",
"BSE651A-Cellular Moleculer Biology",
"BSE652A-Developmental Biology",
"BSE653A-Functional Genomics",
"BSE654A-Human Molecular Genetics",
"BSE655A-PHYSIOLOGY",
"BSE656A-NEUROBIOLOGY",
"BSE680A-BIOPHAMACEUTICALS",
"BSE681A-Biology Laboratory",
"ESO206A-Principles of Biotechnology",
"LIF101A-Introduction to Biology"
] },

{ name: 'Chemical Engineering', link: 'Chemical Engineering',courses: [
"CHE211a-Fluid Mechanics And Its Application",
"CHE221a-Chemical Engineering Thermodynamics",
"CHE251a-Introduction To Che And Process Calculation",
"CHE261a-Chemical Process Industries",
"CHE300a-Chemical Engineering Communication Skills",
"CHE312a-Heat Transfer and Its Applications",
"CHE313a-Mass Transfer and Its Applications",
"CHE331a-Chemical Reaction Engineering",
"CHE349a-UG PROJECT (UGP-I)",
"CHE352a-Chemical Process Simulation Lab",
"CHE362a- Biochemical Engineering",
"CHE381a-Process Control",
"CHE391a-Unit Operation Laboratory -I",
"CHE398a-UG Project II",
"CHE399a-Chemical Engineering Communication Skills",
"CHE453a-Chemical Engineering Design",
"CHE463a-Electronic Polymeric and Ceramic Materials and Processing",
"CHE492a-Unit Operations And Process Control Laboratory",
"CHE494a-Summer In-Plant Training",
"CHE497a-Under Graduate Project-II",
"CHE601a-Fundamentals Of Chemical Engineering -I",
"CHE602a-Fundamentals Of Chemical Engineering -II",
"CHE611a-Transport Phenomena",
"CHE613a-The Structure and Rheology Of Complex Fluids",
"CHE618a-New Separation Processes",
"CHE621a-Thermodynamics",
"CHE622a-Introduction To Molecular Simulations",
"CHE631a-Chemical Reaction Engineering",
"CHE641a-Mathematical Methods In Chemical Engineering",
"CHE633a-Principles Of Heterogeneous Catalysis",
"CHE642a-Numerical Methods In Chemical Engineering",
"CHE652a-Optimization",
"CHE659a- Process Engineering Principles In Micro. Fabrication",
"CHE661a-Analytical and Material Characterization Techniques Of Engineers",
"CHE662a-Petroleum Refinery Engineering",
"CHE674a-Introduction To Nanoscience And Technology",
"CHE676a-Engineering Applications Of Rheology",
"CHE678a-Mechanics Of Soft Materials",
"CHE679a-Special Topics",
"CHE681a-Advanced Process Dynamics and Control",
"CHE684a-An Introduction To Systems Biology ",
"CHE688a-Fundmental Of Colloid and Interface Science and Technology",
"CHE701a-M. Tech. Seminar",
"ESO204a-Fluid Mechanics And Rate Processes"
] },

{ name: 'Civil Engineering', link: 'Civil Engineering',courses: [
"CE211A-Environmental Quality and Pollution",
"CE242A-Civil Engineering Materials",
"CE262A-Engineering Hydraulics",
"CE272A-Structural Analysis",
"CE321A-Engineering Geosciences",
"CE331A-Geoinformatics",
"CE332A-Survey And Geology Camp",
"CE341A-Civil Engineering Communication Skills",
"CE351A-Soil Mechanics",
"CE352A-Foundation Design",
"CE361A-Engineering Hydrology",
"CE371A-Design Of Steel Structures",
"CE372A-Reinforced Cement Concrete Design",
"CE382A-Transportation Engineering",
"CE399A-Technical Communication",
"CE412A-Water Supply And Wastewater Disposal Systems",
"CE441A-Construction Management",
"CE451A-Application Of Geotechnical Engineering",
"CE453A-Civil Engineering Design And Constructon",
"CE454A-Concrete Engineering",
"CE462A-Hydraulic And Hydrologic Design",
"CE471A-Special Topics in Structural Design",
"CE481A-Transportation Facilities Design",
"CE491A-Under Graduate Research -I",
"CE492A-Under Graduate Research -II",
"CE601A-Statistical Analysis For Civil Engineers",
"CE602A-Advanced Mathematics For Civil Engineers",
"CE610A-Advanced Hydrology",
"CE611A-Engineering Hydraulics",
"CE613A-Computer Methods in Hydraulics and Hydrology",
"CE616A-Sediment Transportation",
"CE620A-Structural Dynamics",
"CE621A-Engineering Mechanics",
"CE622A-Stability of Structures",
"CE623A-Experimental Methods in Structurl Engineering",
"CE629A-Earthquake Analysis and Design of Structures",
"CE631A-Advanced Geotechnical Engineering",
"CE637A-Constitutive Modeling Of Frictional Materials",
"CE642A-Geological Hazards",
"CE651A-Special Concretes",
"CE671A-Introduction To Remote Sensing",
"CE674A-Global Navigation Satellite Systems(Gnss)",
"CE676A-Laser Scanning And Photogrammetry",
"CE677A-Geospatial Data Processing",
"CE678A-Introduction To Geodesy",
"CE683A-Traffic Engineering",
"CE689A-Characterization of pavement materials and analysis of pavements",
"CE690A-Laboratory Course In Transportation Engineering",
"CE731A-Risk and Reliability in Geotechnical Engineering",
"EEM602A-Physicochemical principles and process",
"EEM603A-Ecological and biological principles and process",
"EEM606A-Air Pollution And Its Control",
"EEM609A-Modeling Of Natural Systems",
"EEM613A-Atmospheric Physics And Chemistry",
"EEM614A-Principles of environmental economics and management",
"ESO208A-Computational methods in engineering",
"ES640A-Earth System Processes",
"ES642A-Geochemistry",
"ES646A-Global Climate Change",
"ES652A-Igneous And Metamorphic Petrology",
] },

{ name: 'Computer Science and Engineering', link: 'Computer Science and Engineering' ,courses: [
"CS201A-Mathematics For Computer Science -I",
"CS202A-Mathematics For Computer Science -II",
"CS210A-Data Structure And Algorithms",
"CS220A-Computer Organization",
"CS251A-Computing Laboratory-I",
"CS252A-Computing Laboratory II",
"CS300A-Technical Communication",
"CS315A-Principles Of Data Base Systems",
"CS330A-Operating Systems",
"CS335A-Compiler Design",
"CS340A-Theory Of Computation",
"CS345A-Algorithms -II",
"CS350A-Principles Of Programming Langauges",
"CS360A-Introduction To Computer Graphics",
"CS365A-Artificial Intelligence Programming",
"CS396A-UG PROJECT (UGP-II)",
"CS422A-Computer Architecture",
"CS425A-Computer Networks",
"CS433A-Parallel Programming",
"CS455A-Introduction To Software Engineering",
"CS498A-Under Graduate Project-III",
"CS601A-Mathematics For Computer Science",
"CS602A-Design And Analysis Of Algorithms",
"CS618A-Indexing And Searching Techniques In Database",
"CS625A-Advanced Computer Networks",
"CS628A-Computer Systems Security",
"CS632A-Topics In Distributed Systems",
"CS634A-Mobile Computing",
"CS640A-Computational Complexity",
"CS641A-Modern Cryptology",
"CS644A-Finite Automata On Infinite Inputs",
"CS646A-Parallel Algorithms",
"CS647A-Advanced Topics In Algorithms and Data Strcutures",
"CS648A-Randomized Algorithms",
"CS653A-Bioelectricity And Bio-Electronic Devices",
"CS654A-Software Architecture",
"CS663A-Computational Geometry",
"CS671A-Introduction To Natural Language Processing",
"CS676A-Computer Vision And Image Processing",
"CS679A-Machine Learning For Computer Vision",
"CS680A-Category Theory",
"CS681A-Computational Number Theory And Algebra",
"CS682A-Quantum Computing",
"CS683A-Computational Arithmetic-Geometry and Applications",
"CS687A-Algorithmic Information Theory",
"CS697A-Special Topics In Computer Science",
"CS698A-Special Topics In : Game Theory And Its Applications In Computer Science",
"CS719A-Data Streaming: Algorithms and Systems",
"CS743A-Advanced Graph Algorithms",
"CS746A-Riemann Hypothesis and Its Applications",
"CS771A-Machine Learning Techniques",
"ESC101A-Fundamentals Of Computing",
"ESO207A-Data Structures and Algorithms",
"SE367A-Introduction To Cognitive Science"
]
},

{ name: 'Electrical Engineering', link: 'Electrical Engineering', courses: [
"EE200A-Signals, systems and networks",
"EE210A-Microelectronics-I",
"EE250A-Control systems analysis",
"EE301A-Digital signal processing",
"EE311A-Microelectronics II",
"EE320A-Principles of communication",
"EE321A-Communication system",
"EE330A-Power systems",
"EE340A-Electromagnetic theory",
"EE360A-Power electronics",
"EE370A-Digital electronics",
"EE380A-Electrical Engineering Lab I",
"EE381A-Electrical engineering laboratory -II",
"EE390A-Electrical engineering communication skills",
"EE392A-Under graduate project II",
"EE393A-Electrical engineering under graduate project I",
"EE395A-Electrical engineering under graduate project III",
"EE399A-Electrical Engineering Communication Skills",
"EE401A-Electrical engineering communication skills",
"EE442A-Antennas and propagation",
"EE491A-Under graduate project -III",
"EE600A-Mathematical structures of signals and systems",
"EE601A-Mathematical methods in signal processing",
"EE602A-Statistical signal processing-I",
"EE604A-Image processing",
"EE606A-Architecture and applications of digital signal processors",
"EE607A-Wavelet Transforms for Signal and Image Processing",
"EE608A-Digital Video Signal Processing",
"EE610A-Analog/digital VLSI Circuits",
"EE611A-Organic electronics",
"EE612A-Fiber optic systems I",
"EE614A-Solid state devices I",
"EE616A-Semiconductor device modelling",
"EE618A-Integrated circuit fabrication technology",
"EE619A-Vlsi system design",
"EE621A-Representation and analysis of random signals",
"EE622A-Communication theory",
"EE623A-Detection and estimation theory",
"EE624A-Information and coding theory",
"EE626A-Topics in stochastic processes",
"EE627A-Speech signal processing",
"EE629A-Organic electronics",
"EE630A-Simulaton of modern power systems",
"EE631A-Advanced power system stability",
"EE632A-Economic operation and control of power systems",
"EE633A-Electric power system operation and mgmt. Under restructured environment",
"EE634A-Electrical Insulation In Power Apparatus And Systems",
"EE635A-HVDC Transmission and Flexible AC Transmission Systems",
"EE640A-Computational Electromagnetics",
"EE641A-Advanced Engineering Electromagnetics",
"EE642A-Antennas Analysis and Synthesis",
"EE643A-Smart Antennas For Mobile Communication",
"EE644A-Optical Communication",
"EE645A-Monolithic Microwave ICS",
"EE646A-Photonic Networks and Switching",
"EE647A-Microwave measurements and design",
"EE648A-Microwave Circuits",
"EE649A-The Finite Element Method For Electric And Magnetic Fields",
"EE650A-Basics Of Modern Control Systems",
"EE653A-Digital Control",
"EE654A-Robust Control Systems",
"EE658A-Fuzzy Set, Logic and Systems and Applications",
"EE660A-Basics Of Power Electronic Converters",
"EE661A-Power Electronics Applications In Power Systems",
"EE662A-Control Techniques In Power Electronics",
"EE664A-Fundamentals Of Electric Drives",
"EE665A-Advanced electric drives",
"EE666A-Special Topics In Power Electronics",
"EE667A-Information Theory",
"EE668A-Coding Theory",
"EE669A-Simulation Of Communication Systems",
"EE670A-Wireless Communications",
"EE671A-Neural Networks",
"EE673A-Digital Communication Networks",
"EE674A-Architecture Of Micro-Processors and Microcomputers",
"EE678A-Power Electronics In Solar Photovoltaic Systems",
"EE680A-Intelligent Instrument",
"EE681A-Compact Modeling",
"EE686A-Microwave Imaging Characterization And Nondestructive Testing",
"EE698A-Power Management Circuits",
"EE705A-Intelligent Systems and Control",
"ESC201A-Introduction To Electronics",
"ESO203A-Introduction To Electrical Engineering",
] },

{ name: 'Materials Science and Engineering', link: 'Materials Science and Engineering', courses: [
"ESO205A-Nature and Properties of Materials",
"MSE201A-Thermodynamics and Phase Equilibria",
"MSE202A-Rate Processes",
"MSE203A",
"MSE204A",
"MSE300A-Professional and Technical Communication",
"MSE301A-Phase Transformations",
"MSE302A-Mechanical Behaviour of Materials",
"MSE303A-Electronic and Magnetic Properties of Materials",
"MSE304A-Principles of Metals Extraction and Refining",
"MSE305A-Materials Processing",
"MSE311A-Physical Metallurgy Laboratory",
"MSE312A-Functional Materials Laboratory",
"MSE313A-Mechanical Behaviour Laboratory",
"MSE314A-Process Engineering Laboratory",
"MSE315A-Manufacturing Process Laboratory",
"MSE349A-Under Graduate Project I",
"MSE398A-Under Graduate Project II",
"MSE412A-Iron And Steel Making",
"MSE422A-Selection And Design Of Engineering Materials",
"MSE449A-nder Graduate Project IV",
"MSE467A-Materials For Semiconductor Industry",
"MSE604-Science and Technology of Thin Films and Device Fabrication",
"MSE605A-Surface Phenomena And Characterization",
"MSE613A-Electrochemical Technology In Materials Processing",
"MSE615A-Structure and Characterization of Materials",
"MSE616A-Thermodynamics of Materials",
"MSE617A-Mathematics and Computational Methods",
"MSE621A-Xps And Aes In Study Of Surface And Thin Films",
"MSE626A-Transport Phenomena",
"MSE628A-Electronic Devices and Characterization",
"MSE631A-Electroceramic Materials and Applications",
"MSE634A-Fundamentals of Spray Techniques",
"MSE642A-Microscopy and Microanalysis of Materials",
"MSE648A-Diffusion In Solids",
"MSE650A-Fundamentals Of Stereology and Applications To Microstrutural Analysis",
"MSE653A-Transmission Electron Microscopy and Nano-Analysis Of Materials",
"MSE658A-Dislocations and Plasticity",
"MSE659A-Powder Metallurgy",
"MSE664A-Solid State Ionics",
"MSE665A-ractical Transmission Electron Microscopy and Nanoanalysis Of Materials",
"MSE670A-Solidification Processing",
"MSE671A-Heat Treatment and Surface Hardening",
"MSE680A-Grain Boundary Engineering",
"MSE681A-Solar Energy Technologies And Materials",
"MSE682A-Computer Simulations in Materials Science",
"MSE683A-Crystallographic Texture and Mecrostructural Engineering",
"MSE690A-Seminar Participation",
"MSE691A-Seminar Presentation",
"MSE693A-Materials Science Technologies For Applications In Life Sciences",
"MSE694A-Nanostructures And Nanomaterials: Characterization And Properties",
"TA201A-Manufacturing Processes I",
] },

{ name: 'Mechanical Engineering', link: 'Mechanical Engineering', courses: [
"ME621A-INTRODUCTION TO SOLID MECHANICS",
"ME625A-APPLIED DYNAMICS AND VIBRATIONS",
"ME631A-VISCOUS FLOW THEORY",
"ME641A-CONDUCTION AND RADIATION",
"ME642A-CONVECTIVE HEAT AND MASS TRANSFER",
"ME661A-MACHINING SCIENCE I",
"ME662A-MACHINING SCIENCE II",
"ME663A-METAL FORMING",
"ME681A-MATHEMATICS FOR ENGINEERS",
"ME685A-APPLIED NUMERICAL METHODS",
"ME613A-Thermal Environmental Control",
"ME617A-Advanced Theory of Turbomachinery",
"ME622A-Introduction to Continuum Mechanic",
"ME624A-CALCULUS OF VARIATIONS",
"ME626A-Vibration of continuous systems",
"ME627A-NON-LINEAR VIBRATION",
"ME630A-Computational Fluid Dynamics and Heat Transfer",
"ME632A-Geophysical Fluid Dynamics",
"ME634A-Advanced Computational Fluid Dynamics",
"ME639A-Liquid-Vapor Phase Change Technology",
"ME643A-Combustion",
"ME647A-Introduction to Turbulent Flows",
"ME648A-Computer Aided Design of Thermal Systems",
"ME649A-Experimental Methods in Thermal Systems",
"ME660A-RAILROAD VEHICLE DYNAMICS",
"ME664A-FUNDAMENTAL OF CASTING AND SOLIDIFICATION",
"ME668A-MACHINING-DYNAMICS",
"ME669A-MODELLING THERMAL TRANSPORT IN MANUFACTURING PROCESSES",
"ME670A-ADDITIVE MANUFACTURING",
"ME671A-EXPERIMENTAL STRESS ANALYSIS",
"ME672A-MICROMANUFACTURING PROCESSES",
"ME673A-TRANSPORT IN POROUS MEDIA",
"ME676A-NON-LINEAR FINITE ELEMENT METHOD IN SOLID MECHANICS",
"ME682A-DIFFERENCE EQUATIONS FOR ENGINEERS",
"ME685A-APPLIED NUMERICAL METHODS",
"ME689A-MICROSCALE TRANSPORT PHENOMENA",
"ME690A-ALTERNATE FUELS AND ADVANCES IN IC ENGINES",
"ME691A-ENGINE MANAGEMENT",
"ME701A-DESIGN FOR MANUFACTURE AND ASSEMBLY",
"ME720A-THERMOMECHANICS OF DISSIPATING CONTINUA",
"ME721A-THEORY OF PLASTICITY",
"ME722A-DYNAMIC FRACTURE MECHANICS",
"ME723A-WAVE PROPAGATION IN SOLIDS",
"ME724A-MECHANICS OF BIOLOGICAL MEMBRANES",
"ME725A-MICROMECHANICS",
"ME726A-HAMILTONIAN MECHANICS AND SYMPLECTIC ALGORITHMS",
"ME727A-COMPOSITE MATERIAL",
"ME728A-FRACTURE AND FATIGUE",
"ME730A-MODAL ANALYSIS: THEORY AND PRACTICE",
"ME741A-INTERNAL COMBUSTION ENGINES, POLLUTION AND CONTROL",
"ME742A-BOILING AND CONDENSATION",
"ME743A-FUEL CELLS",
"ME745A-Modeling of Turbulent Combustion",
"ME752A-OPTIMIZATION METHODS IN ENGINEERING DESIGN",
"ME756A-PRINCIPLES OF VIBRATION CONTROL",
"ME758A-ADVANCED METHODS IN ENGINEERING DESIGN",
"ME760A-MODERN CONTROL OF DYNAMICS SYSTEM",
"ME761A-Computer Aided Manufacturing",
"ME762A-INTRODUCTION TO ROBOTICS",
"ME763A-ROBOT MANIPULATORS: DYNAMICS AND CONTROL",
"ME765A-MANUFACTURING AUTOMATION",
"ME766A-ROBOT MOTION PLANNING",
"ME771A-SMART MATERIALS AND STRUCTURES",
"ME772A-MECHATRONICS",
"ME773A-GRANULAR MATERIALS",
"ME774A-BIOMEMS",
"ME781A-Approximate Methods in Engineering Mathematics",
"ME850A-BASIC CONTROL SYSTEMS FOR MECHANICAL ENGINEERS"
] },

{ name: 'Chemistry', link: 'Chemistry', courses: [
"CHM101a-Basic Chemistry Lab",
"CHM102a-Basic Chemistry",
"CHM202a-Basic Organic Chemistry -II",
"CHM203a-Basic Organic Chemistry-I",
"CHM222a-Basic Physical Chemistry",
"CHM242a-Basic Inorganic Chemistry",
"CHM303a- Organic Chemistry I",
"CHM305a-Organic qualitative and quantitative analysis",
"CHM321a-Physical Chemistry I",
"CHM322a-Physical Chemistry -II",
"CHM342a-Inorganic Chemistry -II",
"CHM344a-Inorganic Chemistry Laboratory Experiments",
"CHM345a-Inorganic Chemistry I",
"CHM361a-Chemistry Communication Skills",
"CHM391a-Under Graduate Project-I",
"CHM392a-UG Project II",
"CHM399a-Chemistry Communication Skills",
"CHM401a-Organic Chemistry I",
"CHM402a-Organic Chemistry II",
"CHM421a-Physical Chemistry I",
"CHM423a-Physical Chemistry Laboratory",
"CHM441a-Inorganic Chemistry I",
"CHM443a-Inorganic Chemistry Lab",
"CHM481a-Biosystems",
"CHM491a-Under Graduate Project-III",
"CHM521a-Mathematics For Chemistry",
"CHM600a-Mathematics For Chemistry",
"CHM602a-Advanced Organic Chemistry II",
"CHM609a-Principles Of Organic Chemistry",
"CHM611a-Physical Organic Chemistry",
"CHM612a-Frontiers In Organic Chemistry",
"CHM616a-Chemistry Of Organometallic Compounds",
"CHM621a-Chemical Binding",
"CHM626a-Solid State Chemistry",
"CHM627a-Methods Of Electronic Structure Calculation",
"CHM629a-Principles Of Physical Chemistry",
"CHM631a-Applications Of Modern Instrumental Methods",
"CHM636a-Physical Photochemistry",
"CHM637a-Molecular Spectroscopy",
"CHM646a-Bio-inorganic Chemistry I",
"CHM648a-The Chemistry Of Metal-Carbon Bond: Structure Reactivity and Applications",
"CHM649a-Principles Of Inorganic Chemistry",
"CHM650a-Statistical Mechanics and its applications to Chemistry",
"CHM651a-Crystal and Molecular Structure Determination",
"CHM654a-Supramolecular Chemistry",
"CHM662a-Chemistry of Natural Products",
"CHM664a-Modern Physical Methods in Chemistry",
"CHM668a-Advanced Main Group Chemistry",
"CHM676a-Introduction to Bionanotechnology",
"CHM683a-Surfaces, Interfaces, Thin Films and Related Analytical Techniques",
"CHM684a-Computer Programming for Chemistry",
"CHM685a-Molecule Radiation Interaction",
"CHM689a-Nuclear Magnetic Resonance Spectroscopy",
"CHM691a-Frontiers in Inorganic Chemistry",
"CHM695a-Molecular Modelling in Chemistry",
"CHM696a-Quantum Computing",
"CHM698a-Chemistry of Drug Design and Metabolism",
"CHM801a-Graduate Seminar",
"CSO201a-Organic Chemistry: Fundamentals And Applications",
"CSO202a-Atoms, Molecules and Photons",
] },

{ name: 'Earth Sciences', link: 'Earth Sciences', courses:[
"ES640A-Earth System Processes",
"ES642A-Geochemistry",
"ES646A-Global Climate Change",
"ES652A-Igneous And Metamorphic Petrology"
]
},


{ name: 'Economics', link: 'Economics', courses: [
"ECO101A",
"ECO112A-Introducton To Macroeconomic Problems And Policies",
"ECO201-Microeconomics I",
"ECO221A-Microeconomics I",
"ECO226A-Introduction To Mathemetical Economics",
"ECO311A-Development Economics",
"ECO371A-Public Economics And Public Policy",
"ECO408A-Advanced Macro Economics",
"ECO413A-Indian Economic Problems",
"ECO423A-Financial Economics",
"ECO424A-Economic Analysis Of Law",
"ECO501A-Enviromental Economics And Policy",
"ECO541A-Empirical Methods In Applied Microeconomics",
"ECO543A-Bayesian Data Analysis",
"ECO731A-Public Economics And Public Policy",
"ECO732A-Econometrics",
"ECO734A-Industrial Organisation And Policy",
"ECO738A-Inter-Industry Economics",
"ECO745A-Advanced Monetary Theory",
"ECO756A-Programme Evaluation: Methods And Applications"
] },


{ name: 'Mathematics and Scientific Computing', link: 'Mathematics and Scientific Computing', courses: [
"MSO201A-Probability And Statistics",
"MSO202A-Complex Variables",
"MTH101A-Mathematics I",
"MTH102A-Mathematics - II",
"MTH201A-Linear Algebra",
"MTH204A-Abstract Algebra",
"MTH205A-Introduction To Fourier Series",
"MTH215A-Number Theory",
"MTH301A-Analysis- I",
"MTH302A-Mathematical Logic",
"MTH304A-Topology",
"MTH305A-Several Variable Calculus and Defferential Geometry",
"MTH306A-Linear Programming And Extensions",
"MTH308A-Principles Of Numerical Computations",
"MTH311A-Probability Theory - I",
"MTH391A-UG PROJECT (UGP-I)",
"MTH392A-Under Graduate Project",
"MTH393A-Ug Project (UGP-III)",
"MTH399A-Technical Communication",
"MTH401A-Theory Of Computation",
"MTH403A-Complex Analysis",
"MTH404A-Analysis II",
"MTH405A-Functional Analysis",
"MTH409A-Computer Programming And Data Structures",
"Mth412a-Applied Stochastic Process",
"Mth413a-Real And Complex Analysis",
"Mth415a-Matrix Theory And Linear Estimation",
"MTH416A-Regression Analysis",
"MTH417A-Sampling Theory",
"MTH418A-Inference - I",
"MTH421A-Ordinary Differential Equations",
"MTH423A-Introduction To Continuum Machanics",
"MTH424A-Partial Differential Equations",
"MTH426A-An Introduction To Mathematical Modelling",
"MTH428A-Mathematical Methods",
"MTH511A-Statistical Simulation And Data Analysis",
"MTH512A-Foundations Of Mathematical Finance",
"MTH513A-Analysis Of Variance",
"MTH514A-Multivariate Analysis",
"MTH515A-Inference - II",
"MTH516A-Non-Parametric Inference",
"MTH517A-Time Series Analysis",
"MTH522A-Finite Element Method",
"MTH523A-Fluid Mechanics",
"MTH524A-Algorithms",
"MTH611A-Algebra II",
"MTH612A-Introduction To Commutative Algebra",
"MTH620A-Measure Theory",
"MTH621A-Fourier Analysis",
"MTH622A-Fractal Interpolation And Applications",
"MTH624A-Differentiable Manifolds And Lie Groups",
"MTH628A-Topics In Topology",
"MTH631A-Approximation Theory",
"MTH632A-Spectral Theory For Self-Adjoint Operators",
"MTH633A-Introduction To Hyperbolic Geometry",
"MTH638A-Abstract Harmonic Analysis",
"MTH641A-Introduction To Lie Algebras And Representation Theory",
"MTH647A-Complex Analytic Dynamics And Fractals",
"MTH649A-Algebraic Topology",
"MTH653A-Integral Equations",
"MTH656A-Sobolev Spaces And Applications",
"MTH657A-Graph Theory",
"MTH658A-Nonlinear Dynamical Systems",
"MTH664A-Tribology",
"MTH679A-Spatio-Temporal Models In Mathematical Biology",
"MTH686A-Non-Linear Regression",
"MTH691A",
"MTH692A-Numerical Solution Of Ordinary Differential Equations",
"MTH693A-Numerical Solution Of Partial Differential Equations",
"MTH698A-Parallel Numerical Algorithm",
"MTH701A-Modal Logic",
"MTH706A-Numerical Analysis and Scientific Computing",
"MTH719A-Introduction To Homogenization",
"MTH736A-Fourier Analysis-I and Distribution Theory",
"MTH751A-Algebra",
"MTH752A-Mathematical Methods",
"MTH753A-Analysis",
"MTH754A-Probability Theory",
"MTH755A-Statistical Inference",
"MTH759A-Algebric Topology",
]
 },


{ name: 'Physics', link: 'Physics',courses:[
"PHY101A-Physics Laboratory",
"PHY102A-PHYSICS-I",
"PHY103A-PHYSICS-II",
"PHY210A-Thermal Physics",
"PHY224A-OPTICS",
"PHY301A-ENERGY",
"PHY303A-Principles of Lasers and their Applications",
"PHY306A-Order and Chaos in Nature",
"PHY307A-Modern Optics",
"PHY311A-Physics of Non-Eqilibrium Phenomena",
"PHY312A-Quantum Processes in Low Dimensional Semiconductors",
"PHY315A-Modern Physics Laboratory",
"PHY399A-Technical Communication",
"PHY400A-Introduction to the Department",
"PHY401A-Classical Mechanics",
"PHY407A-Special and General Relativity",
"PHY412A-Statistical Mechanics",
"PHY421A-Mathematical Methods I",
"PHY422A-Mathematical Methods II",
"PHY431A",
"PHY432A-Quantum Mechanics II",
"PHY441A-ELECTRONICS",
"PHY461A-Experimental Physics I",
"PHY462A-Experimental Physics II",
"PHY473A-Computational Physics",
"PHY524A-Introduction to Atomic and Nuclear Physics",
"PHY543A-Condensed Matter Physics I",
"PHY553A-Classical Electrodynamics II",
"PHY555A-Batchlor of Science Project - I",
"PHY556A-Batchlor of Science Project - II",
"PHY557A-Batchlor of Science Project - III",
"PHY558A-Batchlor of Science Project - IV",
"PHY590A-Special Topics in Physics",
"PHY600-Introduction to High Performance Computing for Scientists and Engineers",
"PHY601A-Review of Classical Machanics",
"PHY602A-Review of Quantum Mechanics",
"PHY603A-Review of Classical Electrodynamics",
"PHY604A-Review of Statistical Mechanics",
"PHY616A-Soft Matter Physics",
"PHY618A-Physics of Life",
"PHY621A-Electronic Structure of Materials",
"PHY631A-Physics of Semiconductor Nanostructures",
"PHY644A-Quantum Electronics",
"PHY660A-General Relativity and Cosmology",
"PHY663A-Mathematical Methods II",
"PHY664A-Quantum Electronics",
"PHY680A-Particle Physics",
"PHY692A",
"PHY695A-Nonlinear System and Dynamics",
"PHY697A-MSC Research Project -I",
"PHY781A-High Energy Physics II",
"PSO201A-Quantum Physics",
"SE305A-Physics of Non-Equilibrium Phenomena",
"SE312A-Order and Chaos",
"SE314A-Classical Mechanics",
"SE315A-Special and General Relativity",
"SE316A",
]},

{ name: 'Humanities and Social Sciences', link: 'Humanities and Social Sciences',courses: [
"ART101A-Indian Art And Civilization",
"ART102A-Introduction To Art Apreciation and Criticism",
"ART103A-Introduction To Western Art",
"ART105A-Introduction To The Art Of Video Making",
"ART106A-Appreciating Far-Eastern Cinema",
"ART401A-Modern Art",
"ART402A-Principles Of Communication Design",
"ART411A-Methodology: Art Criticism and Appreciation",
"ART701A-Communication Skills: Composition",
"ENG121A-English Language And Composition",
"ENG122A-Introduction To Linguistics",
"ENG123A-Introduction To Literature",
"ENG124A-Language And Society",
"ENG432A-Literature And Ideology",
"ENG433A-Modern Drama",
"ENG436A-The Writer's Vision Of The Future",
"ENG438A-Postcolonial Literature",
"ENG439A-Literature And Censorship",
"ENG701A-Fundamentals Of Modern Linguistics",
"ENG708A-Applied Linguistics",
"ENG712A-Literature And Society",
"ENG716A-Individual Projects",
"ENG733A-Indian Literature",
"ENG750A-Postwar American Fiction",
"PHI141A-Introduction To Philosophy",
"PHI448A-Individual Vs Authority",
"PHI450A-Philosophical Aesthetics",
"PHI455A-Philosophical Logic",
"PHI751A-Twentieth Century Philosophy-I",
"PHI752A-Problems In Philosophical Aesthetics",
"PHI755A-Advanced Topics In Philosophy Of Science",
"PSY151A-Introduction To Psychology",
"PSY454A-Social Psychology",
"PSY458A-Organizational And Administrative Psychology",
"PSY787A-Management Of Organizational Behaviour",
"PSY794A-Disaster Mental Health",
"PSY798A-Advanced Course In Social Cognition",
"SOC171A-Introductory Sociology",
"SOC473A-Indian Society And Culture",
"SOC479A-Indian Society And Culture",
"SOC721A-Sociological Theory",
"SOC745A-Social Theory In Late Twentieth Century ",
"SOC746A-Social Movements : Old And New",
"SOC750A-Sociology Of Religion",
"SOC751A-Methods Of Sociological Research",
"SOC752A-Applied Statistics For Sociologists And Other Social Scientists",
]},

{ name: 'Design Programme', link: 'Design Programme', courses: [
"DES601A-Design Theory",
"DES602A-Design Practice I",
"DES621A-Creative Visualization",
"DES623A-Topics in Motion Pictures",
"DES625A-FORM AND STYLE",
"DES681A-DESIGN PROJECT I",
"DES698A-Special Studies/Project Courses in Design"
]}


];

